version: '3.8'

services:
  client_web:
    build: ./client_web
    depends_on:
      - server
    ports:
      - "8081:8081"
    volumes:
      - ./client_web:/app
      - /app/node_modules
      - /app/.next

  client_mobile:
    build: ./client_mobile
    volumes:
      - ./client_web:/app/client_web
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
