version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: AreaSQL
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: area
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
