import { Inter } from 'next/font/google';
import './globals.css';
import { NextAuthProvider } from './provider'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Breb',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body>
          {children}
          </body>
      </html>
    </NextAuthProvider>
  );
}
